package com.martins.assignmentschronometer.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light Theme Roles ─────────────────────────────────────────────────────────
val LightPrimary              = Color(0xFF5A5769)
val LightOnPrimary            = Color(0xFFFFFFFF)
val LightPrimaryContainer     = Color(0xFFE4DFFF)
val LightOnPrimaryContainer   = Color(0xFF171329)
val LightSecondary            = Color(0xFF72575E)
val LightOnSecondary          = Color(0xFFFFFFFF)
val LightSecondaryContainer   = Color(0xFFFFD9E1)
val LightOnSecondaryContainer = Color(0xFF2B141B)
val LightTertiary             = Color(0xFF775A37)
val LightOnTertiary           = Color(0xFFFFFFFF)
val LightTertiaryContainer    = Color(0xFFFFDDB6)
val LightOnTertiaryContainer  = Color(0xFF281700)
val LightBackground           = Color(0xFFFDF8F4)
val LightOnBackground         = Color(0xFF1C1B1F)
val LightSurface              = Color(0xFFFDF8F4)
val LightOnSurface            = Color(0xFF1C1B1F)
val LightSurfaceVariant       = Color(0xFFE5DFE7)
val LightOnSurfaceVariant     = Color(0xFF49454E)
val LightOutline              = Color(0xFF7A757F)
val LightOutlineVariant       = Color(0xFFCAC4CF)
val LightInverseSurface       = Color(0xFF313034)
val LightInverseOnSurface     = Color(0xFFF4EFF4)
val LightInversePrimary       = Color(0xFFC8C2DA)

// ── Dark Theme Roles ──────────────────────────────────────────────────────────
val DarkPrimary               = Color(0xFFC8C2DA)
val DarkOnPrimary             = Color(0xFF2D2A3F)
val DarkPrimaryContainer      = Color(0xFF434057)
val DarkOnPrimaryContainer    = Color(0xFFE4DFFF)
val DarkSecondary             = Color(0xFFE3BBC5)
val DarkOnSecondary           = Color(0xFF432530)
val DarkSecondaryContainer    = Color(0xFF5A3F46)
val DarkOnSecondaryContainer  = Color(0xFFFFD9E1)
val DarkTertiary              = Color(0xFFEDBC81)
val DarkOnTertiary            = Color(0xFF452C00)
val DarkTertiaryContainer     = Color(0xFF5E4220)
val DarkOnTertiaryContainer   = Color(0xFFFFDDB6)
val DarkBackground            = Color(0xFF1C1B1F)
val DarkOnBackground          = Color(0xFFE6E1E6)
val DarkSurface               = Color(0xFF1C1B1F)
val DarkOnSurface             = Color(0xFFE6E1E6)
val DarkSurfaceVariant        = Color(0xFF49454E)
val DarkOnSurfaceVariant      = Color(0xFFCAC4CF)
val DarkOutline               = Color(0xFF948F99)
val DarkOutlineVariant        = Color(0xFF49454E)
val DarkInverseSurface        = Color(0xFFE6E1E6)
val DarkInverseOnSurface      = Color(0xFF313034)
val DarkInversePrimary        = Color(0xFF5A5769)