changelog:
  exclude:
    labels:
      - ignore-changelog
    authors:
      - github-actions
  categories:
    - title: "🚀 New Features"
      labels:
        - feature
      commits:
        - "feat:*"
        - "feat(*):*"
    - title: "🐛 Bug Fixes"
      labels:
        - bug
      commits:
        - "fix:*"
        - "fix(*):*"
